"""Continue...

Revision ID: 729f92f9d235
Revises: 6379ad687be9
Create Date: 2022-11-24 02:29:10.010799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '729f92f9d235'
down_revision = '6379ad687be9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
