"""Continue2...

Revision ID: e1c55c4db6c8
Revises: 729f92f9d235
Create Date: 2022-11-24 02:31:46.209804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1c55c4db6c8'
down_revision = '729f92f9d235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
